version: '3.3'
services:
  web:
    build: 
      context: ./php
      dockerfile: Dockerfile
    container_name: phpweb
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80

  db:
    image: mysql:8.0
    container_name: mysqlDB
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
    ports:
      - 6033:3306